### ISSUE TITLE
Create the add department feature

### ISSUE THREAD

**Issue by Beingfarazkhan** [Beingfarazkhan/EMS#2]
Create the add department feature for EMS System

**Comment by AKACHI-4** [comment]
Hey @Beingfarazkhan i found this interesting ... i would like to contribute .. can u guide and explain more.. ?

**Comment by Beingfarazkhan** [comment]
Hey @AKACHI-4 Sorry mate but this issue has already been completed, i was just about to close it. If you know php then you can take any other issue mentioned in the issues section. Happy Hacking🧑‍💻
